### ISSUE TITLE
Import statements does no work well on typescript

### ISSUE THREAD

**Issue by mikews93** [tswaters/fireworks#14]
When importing on typescript like this `import * as Fireworks from 'fireworks-canvas'`

when creating the instance it throws this error
![image](https://user-images.githubusercontent.com/17571738/113224678-8e292700-9251-11eb-8ae0-7b4345647fbf.png)

**Comment by tswaters** [comment]
Interesting.  I have this running in one of my typescript projects:

https://github.com/tswaters/klondike/blob/master/src/components/Fireworks.tsx#L3

It doesn't actually _work_ at the moment, ( one of the things I need to fix ) -- but I don't get any typescript errors trying to use it and can build the project OK.

Can you share your project code?  What version of typescript are you using ?

**Comment by mikews93** [comment]
I just used another library, I couldn't figure how to solve the error

**Comment by tswaters** [comment]
OK, thanks.  Closing the ticket.

**Comment by manip-syntax** [comment]
Hello,
I have exactly the same problem. The code is the following :
`import * as Fireworks from 'fireworks-canvas';
const fw = new Fireworks(document.querySelector('body'));
`
Error: 
`This expression is not constructable.
  Type 'typeof Fireworks' has no construct signatures.
`

Typescript version : 4.9.5
Vite version : 4.2.0

If you have any idea on how to solve this, I'm interested ! Thanks in advance !

**Comment by tswaters** [comment]
Yikes, this package.json has some old dependencies.

I think I might do a major bump, update all the things and change to a named export instead of default export.

**Comment by tswaters** [comment]
This should be better now.

Must have been an artifact of old typescript versions... I remember I spent ages trying to get that right.

I've updated the tsconfig to include `"module": "ESNext",` and the latest rollup-typescript plugin does the right thing with it.

Either way, I've published v3.0.0, major change is new build tooling versions & updated to use named export,  `Fireworks`

**Comment by manip-syntax** [comment]
Thank you ! It's perfect !
