### ISSUE TITLE
Support ES5 browser.

### ISSUE THREAD

**Issue by redplane** [tswaters/fireworks#3]
Hi,

I'm using firework-canvas for my personal website using `angular-cli 7`.
In the page that has the firework effect, it cannot be loaded in IE11 but be OK on Google Chrome, Firefox.
Can you compile your dist for ES5 browser ?

**Comment by tswaters** [comment]
I'll see if I can't create a compat version of the code.

How are you loading the package into the page, just a script reference or are you using a module loader like webpack?

**Comment by tswaters** [comment]
`fireworks.js` now has a target of es3.

should be working in v2.3.1
