### ISSUE TITLE
Make fireworks container resizable

### ISSUE THREAD

**Issue by wbobeirne** [tswaters/fireworks#5]
Hey, great little library here! It would be nice if the `FireworksCanvas` class had a `resize` method to update the size of the canvas and start placing fireworks in that boundary.

**Comment by tswaters** [comment]
That's a good idea.  I'll work on this probably in the next few days.

**Comment by tswaters** [comment]
I've added this in the latest release, [v2.4.0](https://github.com/tswaters/fireworks/releases/tag/v2.4.0). Two new methods on the fireworks instance:

* `setSize(width, height)` -- will set the dimensions to the defined size
* `resetSize()` -- will reset the size to that of the container's `clientWidth` and `clientHeight`

Also, you can provide `width` and `height` as options now - they will be defaulted to the container's `clientWidth` and `clientHeight` if not provided.
